<?php

namespace Korama\PruebaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TipoClienteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoClienteRepository extends EntityRepository
{
    public function findAll(){
        $query= $this->getEntityManager() ->createQuery('SELECT a FROM KoramaPruebaBundle:TipoCliente a ORDER BY a.nombre ASC');

        $query->setHint(
            \Doctrine\ORM\Query::HINT_CUSTOM_OUTPUT_WALKER,
            'Gedmo\\Translatable\\Query\\TreeWalker\\TranslationWalker'
        );

        $query->setHint(
            \Gedmo\Translatable\TranslatableListener::HINT_TRANSLATABLE_LOCALE,
            $GLOBALS['kernel']->getContainer()->get('session')->getLocale()
        );

        // fallback
        $query->setHint(
            \Gedmo\Translatable\TranslatableListener::HINT_FALLBACK,
            1 // fallback to default values in case if record is not translated
        );

        return $query->getResult(); 
    }
}