tipoCliente_new:
    pattern:  /{_locale}/tipocliente/new
    defaults: { _controller: KoramaPruebaBundle:TipoCliente:new, _locale: es }
    requirements:
        _locale: es|en
        
tipoCliente_saved:
    pattern:  /{_locale}/tipocliente/saved
    defaults: { _controller: KoramaPruebaBundle:TipoCliente:saved, _locale: es }
    requirements:
        _locale: es|en
cliente_new:
    pattern:  /{_locale}/cliente/new
    defaults: { _controller: KoramaPruebaBundle:Cliente:new, _locale: es }
    requirements:
        _locale: es|en
cliente_saved:
    pattern:  /{_locale}/cliente/saved
    defaults: { _controller: KoramaPruebaBundle:Cliente:saved, _locale: es }
    requirements:
        _locale: es|en

tipocliente_view:
    pattern:  /tipocliente/view/{id}
    defaults: { _controller: KoramaPruebaBundle:TipoCliente:view, id: 0 }
    requirements:
        id: \d*
        
tipocliente_index:        
    pattern:  /tipocliente/index
    defaults: { _controller: KoramaPruebaBundle:TipoCliente:index }
