cliente_index:        
    pattern:  /{_locale}/cliente/index
    defaults: { _controller: KoramaPruebaBundle:Cliente:index, _locale: es }
    requirements:
        _locale: es|en

cliente_edit:
    pattern:  /{_locale}/cliente/edit/{id}
    defaults: { _controller: KoramaPruebaBundle:Cliente:edit, id: 0, _locale: es }
    requirements:
        id: \d*
        _locale: es|en
tipocliente_view:
    pattern:  /{_locale}/cliente/view/{id}
    defaults: { _controller: KoramaPruebaBundle:Cliente:view, id: 0, _locale: es }
    requirements:
        id: \d*
        _locale: es|en

tipocliente_view:
    pattern:  /{_locale}/tipocliente/view/{id}
    defaults: { _controller: KoramaPruebaBundle:TipoCliente:view, id: 0, _locale: es }
    requirements:
        id: \d*
        _locale: es|en
        
tipocliente_index:        
    pattern:  /{_locale}/tipocliente/index
    defaults: { _controller: KoramaPruebaBundle:TipoCliente:index, _locale: es }
    requirements:
        _locale: es|en
tipocliente_edit:
    pattern:  /{_locale}/tipocliente/edit/{id}
    defaults: { _controller: KoramaPruebaBundle:TipoCliente:edit, id: 0, _locale: es }
    requirements:
        id: \d*
        _locale: es|en
        